"""
货币名称映射

常见的加密货币符号到中文名称的映射。

作者: Claude Code
版本: v1.0.0
"""

# 常见货币符号映射
CURRENCY_NAMES = {
    "BTC": "比特币",
    "ETH": "以太坊",
    "BNB": "币安币",
    "USDT": "泰达币",
    "BUSD": "币安稳定币",
    "USDC": "USD Coin",
    "FDUSD": "First Digital USD",
    "ADA": "Cardano",
    "XRP": "瑞波币",
    "SOL": "Solana",
    "DOGE": "狗狗币",
    "DOT": "Polkadot",
    "AVAX": "Avalanche",
    "MATIC": "Polygon",
    "LTC": "莱特币",
    "LINK": "Chainlink",
    "UNI": "Uniswap",
    "ATOM": "Cosmos",
    "XLM": "Stellar",
    "VET": "VeChain",
    "FIL": "Filecoin",
    "TRX": "波场币",
    "ETC": "以太坊经典",
    "XMR": "门罗币",
    "ALGO": "Algorand",
    "HBAR": "Hedera",
    "MANA": "Decentraland",
    "SAND": "The Sandbox",
    "AXS": "Axie Infinity",
    "CRV": "Curve DAO Token",
    "ENJ": "Enjin Coin",
    "BAT": "Basic Attention Token",
    "ZRX": "0x",
    "COMP": "Compound",
    "YFI": "yearn.finance",
    "SUSHI": "SushiSwap",
    "SNX": "Synthetix",
    "GRT": "The Graph",
    "PERP": "Perpetual Protocol",
    "BAL": "Balancer",
    "APE": "ApeCoin",
    "GMT": "Green Metaverse Token",
    "LUNC": "Terra Luna Classic",
    "WBTC": "Wrapped Bitcoin",
    "MASK": "Mask Network",
    "LRC": "Loopring",
    "QTUM": "Qtum",
    "DASH": "Dash",
    "ZEC": "Zcash",
    "XEM": "NEM",
    "WAVES": "Waves",
    "NEO": "NEO",
    "IOTA": "IOTA",
    "ONT": "Ontology",
    "ICX": "ICON",
    "ZIL": "Zilliqa",
    "SC": "Siacoin",
    "DGB": "DigiByte",
    "BTG": "Bitcoin Gold",
    "RVN": "Ravencoin",
    "DCR": "Decred",
    "KAVA": "Kava",
    "BAND": "Band Protocol",
    "STORJ": "Storj",
    "THETA": "Theta Token",
    "ANKR": "Ankr",
    "FET": "Fetch.ai",
    "OCEAN": "Ocean Protocol",
    "CVC": "Civic",
    "TOMO": "Tomochain",
    "DIA": "DIA",
    "BTS": "BitShares",
    "NANO": "Nano",
    "STEEM": "Steem",
    "MAID": "MaidSafeCoin",
    "FUN": "FunToken",
    "SNT": "Status",
    "KMD": "Komodo",
    "SYS": "Syscoin",
    "ARDR": "Ardor",
    "NXT": "Nxt",
    "BURST": "Burst",
    "VERI": "Veritaseum",
    "GXS": "GXShares",
    "PAY": "TenX",
    "EDG": "Edgeware",
    "POLY": "Polymath",
    "POWR": "Power Ledger",
    "REQ": "Request",
    "POE": "Po.et",
    "EOS": "EOS",
}
