"""
告警配置模型

对应数据库 alert_configs 表的 Pydantic 模型。

作者: Claude Code
版本: v2.0.0
"""

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class AlertSignalCreate(BaseModel):
    """Alert signal creation request model."""

    id: str = Field(..., description="Alert UUID (generated by frontend)", max_length=36)
    name: str = Field(..., description="Alert name", max_length=100)
    description: str | None = Field(None, description="Alert description")
    strategy_type: str = Field(
        ...,
        description="Strategy type: macd_resonance, rsi_oversold, etc.",
        max_length=50,
    )
    symbol: str = Field(..., description="Trading pair symbol", max_length=50)
    interval: str = Field(
        ...,
        description="K-line interval (TradingView format: 1, 5, 15, 60, 240, D, W, M)",
        max_length=10,
    )
    trigger_type: str = Field(
        default="each_kline_close",
        description="Trigger type: once_only, each_kline, each_kline_close, each_minute",
    )
    params: dict[str, Any] = Field(
        default_factory=dict,
        description="Strategy parameters JSON",
    )
    is_enabled: bool = Field(default=True, description="Whether alert is enabled")
    created_by: str | None = Field(None, description="Creator identifier", max_length=100)

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "name": "BTC MACD Golden Cross",
                "description": "Alert when MACD golden cross occurs on BTCUSDT",
                "strategy_type": "macd_resonance",
                "symbol": "BINANCE:BTCUSDT",
                "interval": "60",
                "trigger_type": "each_kline_close",
                "params": {
                    "fast1": 12,
                    "slow1": 26,
                    "signal1": 9,
                    "fast2": 5,
                    "slow2": 35,
                    "signal2": 5,
                },
                "is_enabled": True,
            }
        }
    )


class AlertSignalUpdate(BaseModel):
    """Alert signal update request model."""

    name: str | None = Field(None, description="Alert name", max_length=100)
    description: str | None = Field(None, description="Alert description")
    strategy_type: str | None = Field(
        None,
        description="Strategy type",
        max_length=50,
    )
    symbol: str | None = Field(None, description="Trading pair symbol", max_length=50)
    interval: str | None = Field(
        None,
        description="K-line interval",
        max_length=10,
    )
    trigger_type: str | None = Field(
        None,
        description="Trigger type",
    )
    params: dict[str, Any] | None = Field(
        None,
        description="Strategy parameters JSON",
    )
    is_enabled: bool | None = Field(None, description="Whether alert is enabled")

    model_config = ConfigDict(json_schema_extra={
        "example": {
            "name": "BTC MACD Golden Cross Updated",
            "description": "Updated description",
            "is_enabled": False,
        }
    })


class AlertSignalResponse(BaseModel):
    """Alert signal response model."""

    id: UUID = Field(..., description="Alert signal ID")
    name: str = Field(..., description="Alert name")
    description: str | None = Field(None, description="Alert description")
    strategy_type: str = Field(..., description="Strategy type")
    symbol: str = Field(..., description="Trading pair symbol")
    interval: str = Field(..., description="K-line interval")
    trigger_type: str = Field(..., description="Trigger type")
    params: dict[str, Any] = Field(..., description="Strategy parameters")
    is_enabled: bool = Field(..., description="Whether alert is enabled")
    created_at: datetime = Field(..., description="Creation time")
    updated_at: datetime = Field(..., description="Last update time")
    created_by: str | None = Field(None, description="Creator identifier")

    model_config = ConfigDict(from_attributes=True)


class AlertSignalListResponse(BaseModel):
    """Alert signal list response model."""

    items: list[AlertSignalResponse] = Field(..., description="Alert signal list")
    total: int = Field(..., description="Total count")
    page: int = Field(..., description="Current page number")
    page_size: int = Field(..., description="Page size")


class EnableDisableResponse(BaseModel):
    """Enable/disable alert response model."""

    id: UUID = Field(..., description="Alert signal ID")
    name: str = Field(..., description="Alert name")
    is_enabled: bool = Field(..., description="Whether alert is enabled")
    message: str = Field(..., description="Operation result message")


# WebSocket 消息模型
class CreateAlertSignalRequest(BaseModel):
    """WebSocket create alert signal request."""

    type: str = "create_alert_signal"
    name: str = Field(..., description="Alert name", max_length=100)
    description: str | None = Field(None, description="Alert description")
    strategy_type: str = Field(..., description="Strategy type", max_length=50)
    symbol: str = Field(..., description="Trading pair symbol", max_length=50)
    interval: str = Field(..., description="K-line interval", max_length=10)
    trigger_type: str = Field(
        default="each_kline_close",
        description="Trigger type",
    )
    params: dict[str, Any] = Field(default_factory=dict, description="Strategy parameters")
    is_enabled: bool = Field(default=True, description="Whether alert is enabled")

    def __str__(self) -> str:
        return f"CreateAlertSignalRequest(name={self.name}, strategy_type={self.strategy_type})"


class ListAlertSignalsRequest(BaseModel):
    """WebSocket list alert signals request."""

    type: str = "list_alert_signals"
    limit: int = Field(default=100, description="Max records", ge=1, le=500)
    offset: int = Field(default=0, description="Offset", ge=0)
    is_enabled: bool | None = Field(None, description="Filter by enabled status")
    symbol: str | None = Field(None, description="Filter by symbol")
    strategy_type: str | None = Field(None, description="Filter by strategy type")

    def __str__(self) -> str:
        return f"ListAlertSignalsRequest(limit={self.limit}, offset={self.offset})"


class UpdateAlertSignalRequest(BaseModel):
    """WebSocket update alert signal request."""

    type: str = "update_alert_signal"
    id: UUID = Field(..., description="Alert signal ID")
    name: str | None = Field(None, description="Alert name", max_length=100)
    description: str | None = Field(None, description="Alert description")
    strategy_type: str | None = Field(None, description="Strategy type", max_length=50)
    symbol: str | None = Field(None, description="Trading pair symbol", max_length=50)
    interval: str | None = Field(None, description="K-line interval", max_length=10)
    trigger_type: str | None = Field(None, description="Trigger type")
    params: dict[str, Any] | None = Field(None, description="Strategy parameters")
    is_enabled: bool | None = Field(None, description="Whether alert is enabled")

    def __str__(self) -> str:
        return f"UpdateAlertSignalRequest(id={self.id})"


class DeleteAlertSignalRequest(BaseModel):
    """WebSocket delete alert signal request."""

    type: str = "delete_alert_signal"
    id: UUID = Field(..., description="Alert signal ID")

    def __str__(self) -> str:
        return f"DeleteAlertSignalRequest(id={self.id})"


class EnableAlertSignalRequest(BaseModel):
    """WebSocket enable/disable alert signal request."""

    type: str = "enable_alert_signal"
    id: UUID = Field(..., description="Alert signal ID")
    is_enabled: bool = Field(..., description="Whether to enable the alert")

    def __str__(self) -> str:
        return f"EnableAlertSignalRequest(id={self.id}, is_enabled={self.is_enabled})"
