"""
告警配置模型

对应数据库 alert_configs 表的 Pydantic 模型。

作者: Claude Code
版本: v2.1.0
"""

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from ..base import CamelCaseModel, SnakeCaseModel


class AlertConfigCreate(SnakeCaseModel):
    """Alert config creation request model.

    使用 SnakeCaseModel 基类，自动将前端的 camelCase 字段转换为 snake_case。
    """

    id: str = Field(
        ..., description="Alert UUID (generated by frontend)", max_length=36
    )
    name: str = Field(..., description="Alert name", max_length=100)
    description: str | None = Field(None, description="Alert description")
    strategy_type: str = Field(
        ...,
        description="Strategy type: macd_resonance, rsi_oversold, etc.",
        max_length=50,
    )
    symbol: str = Field(..., description="Trading pair symbol", max_length=50)
    interval: str = Field(
        ...,
        description="K-line interval (TradingView format: 1, 5, 15, 60, 240, D, W, M)",
        max_length=10,
    )
    trigger_type: str = Field(
        default="each_kline_close",
        description="Trigger type: once_only, each_kline, each_kline_close, each_minute",
    )
    params: dict[str, Any] = Field(
        default_factory=dict,
        description="Strategy parameters JSON",
    )
    is_enabled: bool = Field(default=True, description="Whether alert is enabled")
    created_by: str = Field(
        ..., description="Creator identifier", max_length=100
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "name": "BTC MACD Golden Cross",
                "description": "Alert when MACD golden cross occurs on BTCUSDT",
                "strategy_type": "macd_resonance",
                "symbol": "BINANCE:BTCUSDT",
                "interval": "60",
                "trigger_type": "each_kline_close",
                "params": {
                    "fast1": 12,
                    "slow1": 26,
                    "signal1": 9,
                    "fast2": 5,
                    "slow2": 35,
                    "signal2": 5,
                },
                "is_enabled": True,
            }
        }
    )


class AlertConfigUpdate(SnakeCaseModel):
    """Alert config update request model.

    使用 SnakeCaseModel 基类，自动将前端的 camelCase 字段转换为 snake_case。
    """

    id: str = Field(
        ..., description="Alert UUID (generated by frontend)", max_length=36
    )
    name: str | None = Field(None, description="Alert name", max_length=100)
    description: str | None = Field(None, description="Alert description")
    strategy_type: str | None = Field(
        None,
        description="Strategy type",
        max_length=50,
    )
    symbol: str | None = Field(None, description="Trading pair symbol", max_length=50)
    interval: str | None = Field(
        None,
        description="K-line interval",
        max_length=10,
    )
    trigger_type: str | None = Field(
        None,
        description="Trigger type",
    )
    params: dict[str, Any] | None = Field(
        None,
        description="Strategy parameters JSON",
    )
    is_enabled: bool | None = Field(None, description="Whether alert is enabled")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "name": "BTC MACD Golden Cross Updated",
                "description": "Updated description",
                "is_enabled": False,
            }
        }
    )


class AlertConfigResponse(CamelCaseModel):
    """Alert config response model.

    使用 CamelCaseModel 基类，序列化时自动将字段转换为 camelCase。
    """

    id: str = Field(..., description="Alert config ID")
    name: str = Field(..., description="Alert name")
    description: str | None = Field(None, description="Alert description")
    strategy_type: str = Field(..., description="Strategy type")
    symbol: str = Field(..., description="Trading pair symbol")
    interval: str = Field(..., description="K-line interval")
    trigger_type: str = Field(..., description="Trigger type")
    params: dict[str, Any] = Field(..., description="Strategy parameters")
    is_enabled: bool = Field(..., description="Whether alert is enabled")
    created_at: datetime = Field(..., description="Creation time")
    updated_at: datetime | None = Field(None, description="Last update time")
    created_by: str | None = Field(None, description="Creator identifier")

    model_config = ConfigDict(from_attributes=True)


class AlertConfigListResponse(CamelCaseModel):
    """Alert config list response model.

    使用 CamelCaseModel 基类，序列化时自动将字段转换为 camelCase。
    """

    items: list[AlertConfigResponse] = Field(..., description="Alert config list")
    total: int = Field(..., description="Total count")
    page: int = Field(..., description="Current page number")
    page_size: int = Field(..., description="Page size")


class EnableDisableResponse(CamelCaseModel):
    """Enable/disable alert response model.

    使用 CamelCaseModel 基类，序列化时自动将字段转换为 camelCase。
    """

    id: UUID = Field(..., description="Alert signal ID")
    name: str = Field(..., description="Alert name")
    is_enabled: bool = Field(..., description="Whether alert is enabled")
    message: str = Field(..., description="Operation result message")


# ==================== WebSocket 响应数据载荷模型 ====================
# 用于 WebSocket 响应的 data 字段，遵循"信封和信"的设计理念
# data 是一个完整的数据模型，而非展开的字典


class AlertConfigData(CamelCaseModel):
    """告警配置数据载荷 - 用于响应 data 字段

    遵循设计文档规范：data 内不包含冗余的 type 字段
    """

    id: str = Field(..., description="Alert config ID")
    name: str = Field(..., description="Alert name")
    description: str | None = Field(None, description="Alert description")
    strategy_type: str = Field(..., description="Strategy type")
    symbol: str = Field(..., description="Trading pair symbol")
    interval: str = Field(..., description="K-line interval")
    trigger_type: str = Field(..., description="Trigger type")
    params: dict[str, Any] = Field(default_factory=dict, description="Strategy parameters")
    is_enabled: bool = Field(..., description="Whether alert is enabled")
    created_at: datetime = Field(..., description="Creation time")
    updated_at: datetime | None = Field(None, description="Last update time")
    created_by: str | None = Field(None, description="Creator identifier")


class AlertConfigListData(CamelCaseModel):
    """告警配置列表数据载荷 - 用于响应 data 字段

    遵循设计文档规范：data 内不包含冗余的 type 字段
    """

    items: list[AlertConfigData] = Field(..., description="Alert config list")
    total: int = Field(..., description="Total count")
    page: int = Field(..., description="Current page number")
    page_size: int = Field(..., description="Page size")


class DeleteAlertData(CamelCaseModel):
    """删除操作响应数据载荷 - 用于响应 data 字段

    遵循设计文档规范：data 内不包含冗余的 type 字段
    """

    id: str = Field(..., description="Deleted alert config ID")
    message: str = Field(default="Alert signal deleted successfully", description="Operation result message")


class SignalData(CamelCaseModel):
    """信号数据载荷 - 用于响应 data 字段

    遵循设计文档规范：data 内不包含冗余的 type 字段
    """

    id: int = Field(..., description="Signal database ID")
    alert_id: str = Field(..., description="Associated alert config ID")
    name: str = Field(..., description="Alert config name at signal creation time")
    strategy_type: str = Field(..., description="Strategy type")
    symbol: str = Field(..., description="Trading pair")
    interval: str = Field(..., description="K-line interval")
    trigger_type: str | None = Field(None, description="Trigger type")
    signal_value: bool | None = Field(None, description="Signal value: true=long, false=short, null=no signal")
    signal_reason: str | None = Field(None, description="Signal reason")
    computed_at: datetime = Field(..., description="Signal computation time")
    source_subscription_key: str | None = Field(None, description="Subscription key that triggered this signal")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional metadata")
    created_by: str | None = Field(None, description="Creator identifier")


class SignalListData(CamelCaseModel):
    """信号列表数据载荷 - 用于响应 data 字段

    遵循设计文档规范：data 内不包含冗余的 type 字段
    """

    items: list[SignalData] = Field(..., description="Signal list")
    total: int = Field(..., description="Total count")
    page: int = Field(..., description="Current page number")
    page_size: int = Field(..., description="Page size")


# WebSocket 消息模型
class CreateAlertConfigRequest(BaseModel):
    """WebSocket create alert config request."""

    type: str = "create_alert_config"
    id: str = Field(..., description="Alert UUID (generated by frontend)", max_length=36)
    name: str = Field(..., description="Alert name", max_length=100)
    description: str | None = Field(None, description="Alert description")
    strategy_type: str = Field(..., description="Strategy type", max_length=50)
    symbol: str = Field(..., description="Trading pair symbol", max_length=50)
    interval: str = Field(..., description="K-line interval", max_length=10)
    trigger_type: str = Field(
        default="each_kline_close",
        description="Trigger type",
    )
    params: dict[str, Any] = Field(
        default_factory=dict, description="Strategy parameters"
    )
    is_enabled: bool = Field(default=True, description="Whether alert is enabled")
    created_by: str = Field(..., description="Creator identifier", max_length=100)

    def __str__(self) -> str:
        return f"CreateAlertConfigRequest(name={self.name}, strategy_type={self.strategy_type})"


class UpdateAlertConfigRequest(BaseModel):
    """WebSocket update alert config request."""

    type: str = "update_alert_config"
    id: UUID = Field(..., description="Alert config ID")
    name: str | None = Field(None, description="Alert name", max_length=100)
    description: str | None = Field(None, description="Alert description")
    strategy_type: str | None = Field(None, description="Strategy type", max_length=50)
    symbol: str | None = Field(None, description="Trading pair symbol", max_length=50)
    interval: str | None = Field(None, description="K-line interval", max_length=10)
    trigger_type: str | None = Field(None, description="Trigger type")
    params: dict[str, Any] | None = Field(None, description="Strategy parameters")
    is_enabled: bool | None = Field(None, description="Whether alert is enabled")

    def __str__(self) -> str:
        return f"UpdateAlertConfigRequest(id={self.id})"


class DeleteAlertConfigRequest(BaseModel):
    """WebSocket delete alert config request."""

    type: str = "delete_alert_config"
    id: UUID = Field(..., description="Alert config ID")

    def __str__(self) -> str:
        return f"DeleteAlertConfigRequest(id={self.id})"


class EnableAlertConfigRequest(BaseModel):
    """WebSocket enable/disable alert config request."""

    type: str = "enable_alert_config"
    id: UUID = Field(..., description="Alert config ID")
    is_enabled: bool = Field(..., description="Whether to enable the alert")

    def __str__(self) -> str:
        return f"EnableAlertConfigRequest(id={self.id}, is_enabled={self.is_enabled})"


# 使用 SnakeCaseModel 的请求模型 - 自动转换 camelCase -> snake_case
class ListAlertConfigsRequest(SnakeCaseModel):
    """List alert configs request model.

    使用 SnakeCaseModel 基类，自动将前端的 camelCase 字段转换为 snake_case。
    """

    page: int = Field(default=1, description="Page number", ge=1)
    page_size: int = Field(default=20, description="Page size", ge=1, le=100)
    is_enabled: bool | None = Field(None, description="Filter by enabled status")
    symbol: str | None = Field(None, description="Filter by symbol")
    strategy_type: str | None = Field(None, description="Filter by strategy type")


class ListSignalsRequest(SnakeCaseModel):
    """List signals request model.

    使用 SnakeCaseModel 基类，自动将前端的 camelCase 字段转换为 snake_case。
    """

    page: int = Field(default=1, description="Page number", ge=1)
    page_size: int = Field(default=20, description="Page size", ge=1, le=100)
    symbol: str | None = Field(None, description="Filter by symbol")
    strategy_type: str | None = Field(None, description="Filter by strategy type")
    interval: str | None = Field(None, description="Filter by interval")
    signal_value: bool | None = Field(None, description="Filter by signal value")
    start_time: datetime | None = Field(None, description="Start time (fromTime in ms)")
    end_time: datetime | None = Field(None, description="End time (toTime in ms)")
